### ISSUE TITLE
ApplicationSets

### ISSUE THREAD

**Issue by dangrondahl** [eficode-academy/argocd-katas#7]
Tasks

- [ ] What are the value props of applicationsets (why?)
- [ ] How does an app-of-app pattern look like for a Applications
- [ ] A bit about generators, understanding that apps are created through appsets (not in a git repo)

**Comment by dangrondahl** [comment]
https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Use-Cases/

**Comment by sofusalbertsen** [comment]
Close:
https://github.com/eficode-academy/argocd-katas/blob/main/applicationsets.md
